<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <!-- 1ª -CONFIGURAÇÃO DO PROJETO -->
    <modelVersion>4.0.0</modelVersion>


    <!-- 2ª  SPRING BOOT PARENT

         Fornece:
         - Gerenciamento de dependências
         - Configuração de plugins
         - Versões padrão das bibliotecas
    -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.0</version>
        <relativePath/>
    </parent>


    <!-- 3ª - VERSÃO DO JAVA

         Java 21 = Versão LTS (Suporte de Longo Prazo)
    -->
    <properties>
        <java.version>21</java.version>
    </properties>


    <!-- 4ª - IDENTIFICAÇÃO DO PROJETO -->
    <groupId>com.dinisjovete</groupId>

    <artifactId>rest-with-springboot-java</artifactId>

    <version>0.0.1-SNAPSHOT</version>

    <name>rest-with-springboot-java</name>

    <description>
        Projeto de API REST desenvolvido com Spring Boot
    </description>


    <!-- 5ª - DEPENDÊNCIAS DO PROJETO -->
    <dependencies>


        <!--
             SPRING WEB

             Fornece:
             - Spring MVC
             - Controllers para API REST
             - Conversão de JSON com Jackson

             Utilizado para criar aplicações web e APIs REST.
        -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>


        <!--
             DEVTOOLS

             Reinicia a aplicação automaticamente durante o
             desenvolvimento sempre que houver alterações no código.
        -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>


        <!--
             SUPORTE A TESTES

             Fornece:
             - JUnit 5
             - Mockito
             - Spring Test
             - MockMvc

             Utilizado para criação de testes automatizados.
        -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>


        <!--
             SPRING DATA JPA

             Fornece suporte para trabalhar com banco de dados usando JPA.

             Inclui:
             - Spring Data Repository
             - JpaRepository
             - Integração com Hibernate (implementação JPA padrão)
             - Gerenciamento de entidades (@Entity)
       -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>


        <!--
             POSTGRESQL DRIVER

             Fornece o driver JDBC para comunicação
             entre a aplicação Java e o banco PostgreSQL.

             O scope runtime indica que ele é necessário
             durante a execução da aplicação.
       -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>


    </dependencies>


    <!-- 6ª - CONFIGURAÇÃO DE BUILD E PLUGINS -->
    <build>

        <plugins>

            <!--
                 Plugin oficial do Spring Boot para compilar,
                 executar e empacotar a aplicação em um arquivo
                 JAR executável.
            -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>

        </plugins>

    </build>


</project>