# ==========================================================
# ATIVAÇÃO DO PERFIL (Obrigatório para rodar o Seed)
# ==========================================================
spring.profiles.active=dev


# ==========================================================
# IDENTIFICAÇÃO DA APLICAÇÃO
# Define o nome da aplicação Spring Boot.
# Pode ser utilizado em logs, monitoramento e Spring Cloud.
# ==========================================================
spring.application.name=rest-with-springboot-java


# ==========================================================
# CONFIGURAÇÃO DO BANCO DE DADOS (POSTGRESQL)
# Define como a aplicação se conecta ao banco PostgreSQL.
# ==========================================================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/rest_with_springboot_java
spring.datasource.username=postgres
spring.datasource.password=1985


# ==========================================================
# CONFIGURAÇÃO DO JPA / HIBERNATE
# Controla como as entidades Java são mapeadas para o banco
# e exibe os comandos SQL gerados durante a execução.
# ==========================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true